apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: k8s-node-deployment
  labels:
    app: k8s-node
    tier: app
spec:
  selector:
    matchLabels:
      app: k8s-node
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-node
        tier: app
    spec:
      containers:
      - image: eslamkarim/voda-node:latest
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: HOST
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: PASSWORD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DATABASE
        name: node-container
        ports:
        - containerPort: 3000